public with sharing class Hello_World {
    public Hello_World() {
System.debug('Hello World jojo !!!');
System.debug('Hxxxxello World  !!!');
System.debug('Hxxxxello World  !!!');
System.debug('tttttttttttttt !!!');
System.debug('fffffffff !!!');
System.debug('vvvvvvvvv !!!');

System.debug('kmnbkfdjl Wdsborld  !!!');
System.debug('kmnbkfdjl Wdsborld  !!!');
System.debug('kmnbkfdjl Wdsborld  !!!');
System.debug('kmnbkfdjl Wdsborld  !!!');
    }
}
